lib/pulap_web/router.ex
defmodule PulapWeb.Router do
  use PulapWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Pulap.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PulapWeb do
    pipe_through [:browser] # Use the default browser stack
    get "/", PageController, :index
    get "/signup", UserController, :signup
    post "/signup", UserController, :signup
    get "/signin", SessionController, :init_signin
    post "/signin", SessionController, :signin
  end

  scope "/", PulapWeb do
    pipe_through [:browser, :auth] # Use the default browser stack
    get "/signout", SessionController, :signout
  #   get "/", PageController, :index
  #   get "/signup", UserController, :signup
  #   post "/signup", UserController, :signup
  #   get "/signin", SessionController, :signin
  #   post "/signin", SessionController, :signin
  end

  scope "/", PulapWeb do
    pipe_through [:browser, :auth, :ensure_auth] # Use the default browser stack
    get "/dashboard", DashboardController, :index
    resources "/users", UserController do
      get "/profile/edit", ProfileController, :edit
      get "/profile", ProfileController, :show
      patch "/profile", ProfileController, :update
      put "/profile", ProfileController, :update
    end
    resources "/organizations", OrganizationController do
      # nested resources
    end
    resources "/roles", RoleController do
      # nested resources
    end
    resources "/permissions", PermissionController do
      # nested resources
    end
    resources "/resources", ResourceController do
      # nested resources
    end
    resources "/role-permissions", RolePermissionController do
      # nested resources
    end
    resources "/resource-permissions", ResourcePermissionController do
      # nested resources
    end
    resources "/user-roles", UserRoleController do
      # nested resources
    end
    resources "/properties", PropertyController do
      # nested resources
    end
    resources "/property-sets", PropertySetController do
      # nested resources
    end
    resources "/plans", PlanController do
      # nested resources
    end
    resources "/plan-subscriptions", PlanSubscriptionController do
      # nested resources
    end
    resources "/key-values", KeyValueController do
      # nested resources
    end
    resources "/geo-areas", GeoAreaController do
      # nested resources
    end
    resources "/currencies", CurrencyController do
      # nested resources
    end
    resources "/real_estates", RealEstateController do
      # nested resources
    end
    resources "/tenures", TenureController do
      # nested resources
    end
    resources "/administratorships", AdministratorshipController do
      # nested resources
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PulapWeb do
  #   pipe_through :api
  # end
end

lib/pulap_web/templates/resource/edit.html.eex
<h2>Edit Resource</h2>

<%= render "form.html", Map.put(assigns, :action, resource_path(@conn, :update, @resource)) %>

<span><%= link "Back", to: resource_path(@conn, :index) %></span>

lib/pulap_web/templates/resource/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :id, class: "control-label" %>
    <%= text_input f, :id, class: "form-control" %>
    <%= error_tag f, :id %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :tag, class: "control-label" %>
    <%= text_input f, :tag, class: "form-control" %>
    <%= error_tag f, :tag %>
  </div>

  <div class="form-group">
    <%= label f, :organization_name, class: "control-label" %>
    <%= text_input f, :organization_name, class: "form-control" %>
    <%= error_tag f, :organization_name %>
  </div>

  <div class="form-group">
    <%= label f, :is_active, class: "control-label" %>
    <%= checkbox f, :is_active, class: "checkbox" %>
    <%= error_tag f, :is_active %>
  </div>

  <div class="form-group">
    <%= label f, :is_logical_deleted, class: "control-label" %>
    <%= checkbox f, :is_logical_deleted, class: "checkbox" %>
    <%= error_tag f, :is_logical_deleted %>
  </div>

  <div class="form-group">
    <%= label f, :started_at, class: "control-label" %>
    <%= datetime_select f, :started_at, class: "form-control" %>
    <%= error_tag f, :started_at %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/pulap_web/templates/resource/index.html.eex
<h2>Listing Resources</h2>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Tag</th>
      <th>Organization name</th>
      <th>Is active</th>
      <th>Is logical deleted</th>
      <th>Started at</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for resource <- @resources do %>
    <tr>
      <td><%= resource.id %></td>
      <td><%= resource.name %></td>
      <td><%= resource.description %></td>
      <td><%= resource.tag %></td>
      <td><%= resource.organization_name %></td>
      <td><%= resource.is_active %></td>
      <td><%= resource.is_logical_deleted %></td>
      <td><%= resource.started_at %></td>

      <td class="text-right">
        <span><%= link "Show", to: resource_path(@conn, :show, resource), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: resource_path(@conn, :edit, resource), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: resource_path(@conn, :delete, resource), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Resource", to: resource_path(@conn, :new) %></span>

lib/pulap_web/templates/resource/new.html.eex
<h2>New Resource</h2>

<%= render "form.html", Map.put(assigns, :action, resource_path(@conn, :create)) %>

<span><%= link "Back", to: resource_path(@conn, :index) %></span>

lib/pulap_web/templates/resource/show.html.eex
<h2>Show Resource</h2>

<ul>

  <li>
    <strong>Id:</strong>
    <%= @resource.id %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @resource.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @resource.description %>
  </li>

  <li>
    <strong>Tag:</strong>
    <%= @resource.tag %>
  </li>

  <li>
    <strong>Organization name:</strong>
    <%= @resource.organization_name %>
  </li>

  <li>
    <strong>Is active:</strong>
    <%= @resource.is_active %>
  </li>

  <li>
    <strong>Is logical deleted:</strong>
    <%= @resource.is_logical_deleted %>
  </li>

  <li>
    <strong>Started at:</strong>
    <%= @resource.started_at %>
  </li>

</ul>

<span><%= link "Edit", to: resource_path(@conn, :edit, @resource) %></span>
<span><%= link "Back", to: resource_path(@conn, :index) %></span>